version: "3.3"

services:
  dev:
    container_name: lgt_gateway_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      dockerfile: DOCKERFILE
    command: npm run start:debug
    ports:
      - 8000:8000
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
networks:
  nesjs-network:
